// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Kbl4P9xTM6Tiuh5Hi_EFpkqXqNie8iE',
    appId: '1:31432783698:web:60bf6cb707db6e4945ac8b',
    messagingSenderId: '31432783698',
    projectId: 'regen-f1dbf',
    authDomain: 'regen-f1dbf.firebaseapp.com',
    storageBucket: 'regen-f1dbf.firebasestorage.app',
    measurementId: 'G-16HS37HX3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ySMpT89P2wB3t4WvZyqccyJZ9HSLJQA',
    appId: '1:31432783698:android:62363eecfa05d87945ac8b',
    messagingSenderId: '31432783698',
    projectId: 'regen-f1dbf',
    storageBucket: 'regen-f1dbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnAAHoQnVKIhNuLGbAA6-gHK9NfnC5S-o',
    appId: '1:31432783698:ios:8128b2937bd7358b45ac8b',
    messagingSenderId: '31432783698',
    projectId: 'regen-f1dbf',
    storageBucket: 'regen-f1dbf.firebasestorage.app',
    iosBundleId: 'com.example.regenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnAAHoQnVKIhNuLGbAA6-gHK9NfnC5S-o',
    appId: '1:31432783698:ios:8128b2937bd7358b45ac8b',
    messagingSenderId: '31432783698',
    projectId: 'regen-f1dbf',
    storageBucket: 'regen-f1dbf.firebasestorage.app',
    iosBundleId: 'com.example.regenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Kbl4P9xTM6Tiuh5Hi_EFpkqXqNie8iE',
    appId: '1:31432783698:web:80ee5931ec5820cc45ac8b',
    messagingSenderId: '31432783698',
    projectId: 'regen-f1dbf',
    authDomain: 'regen-f1dbf.firebaseapp.com',
    storageBucket: 'regen-f1dbf.firebasestorage.app',
    measurementId: 'G-8GY9JBE44W',
  );
}
